### PR TITLE
[Work in progress] Initial PyConTW 2018 project

### PR DESCRIPTION
**Pull request by keitheis**
## Purpose

Open 2018 project and first page.

## Changes

Inherited fundamental pages and materials from 2017. Most of then are copied and requiring no review.

## What to review

- What files copied (not the content copied from 2017)
- `requirements/dev.txt`

### CODE REVIEW

**Comment by keitheis** [comment]
@uranusjr 全都是 copied 的啊，沒什麼真要看的，就看是不是 copy 這些檔案吧。XD

**Comment by keitheis** [comment]
@uranusjr 沒真要看的，所以就先謝謝你的 review 囉這樣？XD See you later.

**Comment by uranusjr** [comment]
🙄

**Comment by keitheis** [comment]
These tests are ... eyesawesome 👀

**Comment by keitheis** [comment]
Going to redo from another aspect.

**Pull request closed without merging**
