### PR TITLE
Add tutorial info

### PR DESCRIPTION
**Pull request by ccwang002**
Originally made by @chairco in #274

### CODE REVIEW

**Comment by ccwang002** [comment]
@chairco 幫忙看一下有沒有問題~

**Comment by ccwang002** [comment]
我自認沒問題，merge 囉 xd

**Comment by ccwang002** [comment]
@daikeren 麻煩了 > <

**Comment by chairco** [comment]
@ccwang002  clone 下來一份確認過，沒問題。
只是在 tutorial 英文頁面：
Ticket Info
The tutorial Creating python app with MySQL Router and MySQL Group Replication are only availabe for those who have already bought tickets for PyCon.。

我有誤打了一個全形的 "。"

**Pull request merged**
